from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('nearby/', views.nearby, name="nearby"),


    path('newsfeed/', views.newsfeed, name="newsfeed"),
    path('logout/', views.logout, name="logout"),
    path('index-company/', views.indexcompany, name="index-company"),
    path('landing/', views.landing, name="landing"),
    path('time-line.html/', views.timeline, name="time-line"),
    path('timeline-friends/', views.timelinefriends, name="timeline-friends"),
    path('timeline-groups/', views.timelinegroups, name="timeline-groups"),
    path('timeline-pages/', views.timelinepages, name="timeline-pages"),
    path('timeline-photos/', views.timelinephotos, name="timeline-photos"),
    path('timeline-videos/', views.timelinevideos, name="timeline-videos"),
    path('groups/', views.groups, name="groups"),
    path('page-likers/', views.pagelikers, name="page-likers"),
    path('fav-page/', views.favpage, name="fav-page"),
    path('create-fav-page/', views.favpage, name="create-fav-page"),
    path('edit-account-setting/', views.editaccountsettings, name="edit-account-setting"),
    path('edit-interest/', views.editinterest, name="edit-interest"),
    path('edit-password/', views.editpassword, name="edit-password"),
    path('edit-profile-basic/', views.profilebasic, name="edit-profile-basic"),
    path('edit-work-eductation/', views.workeductation, name="edit-work-eductation"),
    path('timeline-videos/', views.timelinevideos, name="timeline-videos"),
    path('messages/', views.message, name="messages"),
    path('inbox/', views.inbox, name="inbox"),
    path('notifications/', views.notification, name="notifications"),
    path('forum/', views.forum, name="forum"),
    path('forum-category/', views.forumcategory, name="forums-category"),
    path('forum-open-topic/', views.opentopic, name="forum-open-topic"),
    path('forum-create-topic/', views.createtopic, name="forum-create-topic"),
    path('shop/', views.shop, name="shop"),
    path('shop-masonry/', views.shopmasonry, name="shop-masonry"),
    path('shop-single/', views.shopsingle, name="shop-single"),
    path('shop-cart/', views.shopcart, name="shop-cart"),
    path('shop-checkout/', views.shopcheckout, name="shop-checkout"),
    path('blog-grid-wo-sidebar/', views.wosidebar, name="blog-grid-wo-sidebar"),
    path('blog-grid-right-sidebar/', views.rightsidebar, name="blog-grid-right-sidebar"),
    path('blog-grid-left-sidebar/', views.leftsidebar, name="blog-grid-left-sidebar"),
    path('blog-list-wo-sidebar/', views.listwo, name="blog-list-wo-sidebar"),
    path('blog-list-right-sidebar/', views.listright, name="blog-list-right-sidebar"),
    path('blog-list-left-sidebar/', views.listleft, name="blog-list-left-sidebar"),
    path('blog-masonry/', views.blogmasonry, name="blog-masonry"),
    path('blog-detail/', views.blogdetail, name="blog-detail"),
    path('portfolio-2colm/', views.portfolio2colm, name="portfolio-2colm"),
    path('portfolio-3colm/', views.portfolio3colm, name="portfolio-3colm"),
    path('portfolio-4colm/', views.portfolio4colm, name="portfolio-4colm"),
    path('support-and-help/', views.support, name="support-and-help"),
    path('support-and-help-detail/', views.supportdetail, name="support-and-help-detail"),
    path('support-and-help-search-result/', views.supportsearch, name="support-and-help-search-result"),
    path('careers/', views.careers, name="careers"),
    path('career-detail/', views.careerdetail, name="career-detail"),
    path('404/', views.f404, name="404"),
    path('faq/', views.faq, name="faq"),
    path('insights/', views.insights, name="insights"), 
    path('knowledge-base/', views.knowledgebase, name="knowledge-base"),
    path('about/', views.about, name="about"),
    path('about-company/', views.aboutcompany, name="about-company"),
    path('contact/', views.contact, name="contact"),
    path('contact-branches/', views.contactbranches, name="contact-branches"),
    path('widgets/', views.widgets, name="widgets"),
    path('sitemap/', views.sitemap, name="sitemap"),
    path('terms/', views.terms, name="terms"),
    


]